import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import { AppShellComponent } from "@/components/AppShellComponent";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className={inter.className}>
				<SessionProvider>
					<MantineProvider>
						<AppShellComponent children={children} />
						{/* {children} */}
					</MantineProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
